# Generated by Django 4.1.4 on 2023-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('req', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fl', models.FileField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='reqtno',
            fields=[
                ('requestnumber', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
