# Generated by Django 4.1.4 on 2023-01-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convertapp', '0002_remove_files_date_remove_files_time_files_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='datetime',
            new_name='date',
        ),
    ]
